"""Student

Revision ID: 509e080a192d
Revises: 052c6c408536
Create Date: 2024-06-06 21:22:59.704925

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "509e080a192d"
down_revision: Union[str, None] = "052c6c408536"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("name", sa.String(), nullable=True))
    op.drop_constraint("students_user_id_key", "students", type_="unique")
    op.drop_constraint("students_user_id_fkey", "students", type_="foreignkey")
    op.drop_column("students", "user_id")
    op.drop_column("students", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students",
        sa.Column(
            "role",
            postgresql.ENUM("GUEST", "ADMIN", "STUDENT", "TEACHER", name="role"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "students",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "students_user_id_fkey", "students", "users", ["user_id"], ["id"]
    )
    op.create_unique_constraint("students_user_id_key", "students", ["user_id"])
    op.drop_column("students", "name")
    # ### end Alembic commands ###
